options:
  config_file: anvil.yaml
  temp_dir: /tmp/anvil
  pwd:
debug:
  level: 1
  class_color: "cyan"
  function_color: "purple"
  changed_color: "yellow"
  error_color: "red"
  ok_color: "green"
  info_color: "gray"
projects:
s_group:
  hosts:
  name:
  path:
  var_file_path:
s_host:
  group:
  name:
  path:
  var_file_path:
s_project:
  ansible_config_file:
  groups:
  groups_list:
  hosts:
  hosts_list:
  inventory_file:
  name:
  path:
  playbooks_directory:
  repo_url:
  tree_file:
