projects:
  Peddle:
    ansible_config_file_path: /home/nathan/Development/BarrowsHPC-Configs/configuration_files/ansible.cfg
    groups:
      all: null
      all:!auth:!storage: null
      all:!storage: null
      auth:
        hosts:
          peddle-cluster-auth: null
          peddle-cluster-keycloak: null
      login:
        hosts:
          peddle-cluster-login: null
      management:
        hosts:
          peddle-cluster-mgmt: null
      storage:
        hosts:
          peddle-cluster-storage0: null
      workers:
        hosts:
          peddle-cluster-worker0: null
    groups_list:
    - all
    - all:!storage
    - all:!auth:!storage
    - storage
    - workers
    - management
    - login
    - auth
    hosts:
    - peddle-cluster-storage0
    - peddle-cluster-worker0
    - peddle-cluster-mgmt
    - peddle-cluster-login
    - peddle-cluster-auth
    - peddle-cluster-keycloak
    inventory_file_path: /home/nathan/Development/BarrowsHPC-Configs/configuration_files/inventory.yml
    playbooks_directory: /home/nathan/Development/BarrowsHPC-Configs/playbooks
    project_dir: /home/nathan/Development/BarrowsHPC-Configs/configuration_files
    repo_url: ''
    tree_file_path: /home/nathan/Development/BarrowsHPC-Configs/configuration_files/tree.yaml
    variables_file_path: /home/nathan/Development/BarrowsHPC-Configs/playbooks/variables.yml
s_group: login
s_host: peddle-cluster-login
s_project: Peddle
