current_project: Peddle-Configs
projects:
  Peddle-Configs:
    ansible_config_file_path: /home/nathan/Development/Anvil/repo/Peddle-Configs/ansible.cfg
    groups:
      auth:
        hosts:
          peddle-cluster-auth: null
      login:
        hosts:
          peddle-cluster-login: null
      management:
        hosts:
          peddle-cluster-mgmt: null
      storage:
        hosts:
          peddle-cluster-storage0: null
      workers:
        hosts:
          peddle-cluster-worker0: null
    groups_list:
    - storage
    - workers
    - management
    - login
    - auth
    hosts:
    - peddle-cluster-storage0
    - peddle-cluster-worker0
    - peddle-cluster-mgmt
    - peddle-cluster-login
    - peddle-cluster-auth
    inventory_file_path: /home/nathan/Development/Anvil/repo/Peddle-Configs/inventory.yml
    project_dir: /home/nathan/Development/Anvil/repo/Peddle-Configs
    repo_url: git@git-ssh.gravityfargo.dev:gravityfargo/Peddle-Configs.git
    tree_file_path: /home/nathan/Development/Anvil/repo/Peddle-Configs/tree.yaml
s_host: peddle-cluster-login
s_project: Peddle-Configs
